# Generated by Django 5.1.5 on 2025-04-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_orderaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(default='M', max_length=5),
        ),
    ]
