# Generated by Django 5.1.5 on 2025-03-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Premium', 'Premium'), ('Accessories', 'Accessories')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price_inr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image1', models.ImageField(upload_to='products/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
