# Generated by Django 5.1.5 on 2025-03-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Premium', 'Premium'), ('Accessories', 'Accessories'), ('T-Shirts', 'T-Shirts')], max_length=20),
        ),
    ]
