# Generated by Django 5.1.5 on 2025-04-08 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='custom_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='custom_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
