# Generated by Django 5.1.5 on 2025-04-14 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_custom_image_url_product_custom_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='custom_image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
