# Generated by Django 5.1.5 on 2025-04-14 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_custom_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='custom_image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
